### ISSUE TITLE
alternative for django-ninja permission

### ISSUE THREAD

**Issue by neodark** [baseplate-admin/Blog#41]
Hi! 
Thanks for your great article on the implementation of django-ninja custom permissions.

While searching for different alternatives, I fell on this: "django-ninja-extra":

https://eadwincode.github.io/django-ninja-extra/

which seems pretty much advanced and could answer the issue of permissions in django-ninja.

I just thought worth mentioning and sharing it with you.

Best regards.

**Comment by baseplate-admin** [comment]
Hi, as a matter of fact, I personally used the `django-ninja-extra` myself.

So i will share some of my opinion on this : 

> While searching for different alternatives, I fell on this: [`django-ninja-extra`](https://eadwincode.github.io/django-ninja-extra/):

Yep, I know `django-ninja-extra`, ( [fun fact, the creator of the project helped me to come up with the idea](https://github.com/eadwinCode/django-ninja-extra/issues/60) ). 
So my gripes with the `django-ninja-extra` library are:
* It gives me too much. ( I dont want to use 95% of the functionality of what `django-ninja-extra` provides )
* The configuration is done is `settings.py` ( I might have different requirements for each of the entry points, so having a default doesn't make sense, at least to me )
* It installs `ninja-schema` ( I dont like this dependency, ideally the package should be dependency free, it should call into cores of `django-ninja`, so this feels like a shim on top of a shim )

> which seems pretty much advanced and could answer the issue of permissions in django-ninja.

Absolutely. If you like having a library that does it for you it's completely fine to use that. But i wanted to learn how to do it myself ( to learn the logic and customize it for my specific project )


>  Thanks for your great article on the implementation of django-ninja custom permissions.

You are most welcome

**Comment by neodark** [comment]
Thanks for your point of view. I had the intuition that `django-ninja-extra` was too heavy for a project I am working on.

As you mentioned, it seems quite advanced in terms of development (release, etc.) but I'm on the same journey to learn how to do it myself and your blog post is a very good starting point.

Sorry for disturbing you by the way and thanks again, have a great day!

**Comment by baseplate-admin** [comment]
> Sorry for disturbing you by the way and thanks again, have a great day!

I dont mind actually. if you want to ask more questions feel free :D 

Have a good day too
